
--Tasks Find employees earning more than average salary 
SELECT EMP_ID,EMP_NAME,SALARY
FROM EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY)FROM EMPLOYEES)

--Find department with highest total salary 
SELECT D.DEPT_NAME, SUM(E.SALARY) AS TOTAL_SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME
ORDER BY TOTAL_SALARY DESC;

--Display employee with second highest salary 
SELECT EMP_ID,EMP_NAME,SALARY
FROM EMPLOYEES 
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES 
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES)
);

--Display employees working in same department as "Amit"	
SELECT EMP_ID,EMP_NAME,SALARY,DEPT_ID
FROM EMPLOYEES
WHERE DEPT_ID=( SELECT DEPT_ID FROM EMPLOYEES WHERE EMP_NAME = 'AMIT');