--Database: company_db 
--Tables employees( emp_id INT, emp_name VARCHAR(50), dept_id INT, salary INT ) 
--departments( dept_id INT, dept_name VARCHAR(50) ) 

CREATE DATABASE COMPANY_DB;
USE COMPANY_DB;

CREATE TABLE EMPLOYEES(
EMP_ID INT,
EMP_NAME VARCHAR(50),
DEPT_ID INT,
SALARY INT,
);
CREATE TABLE DEPARTMENTS(
DEPT_ID INT,
DEPT_NAME VARCHAR(50)
)

INSERT INTO EMPLOYEES VALUES
(11,'MEET',50,50000),
(12,'HET',40,40000),
(13,'SANJAY',40,40000),
(14,'HARSH',50,50000)

INSERT INTO DEPARTMENTS VALUES
(50,'AI/ML'),
(40,'.NET')

SELECT * FROM EMPLOYEES
SELECT * FROM DEPARTMENTS

--Tasks Display employee name with department name 
SELECT EMPLOYEES.EMP_NAME,DEPARTMENTS.DEPT_NAME 
FROM EMPLOYEES JOIN DEPARTMENTS 
ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID; 

--Display employees earning more than 40,000 
SELECT * FROM EMPLOYEES WHERE SALARY>40000;

--Display department-wise total salary Display
SELECT D.DEPT_NAME,SUM(E.SALARY) AS TOTAL_SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY D.DEPT_NAME;

--departments with more than 2 employees
SELECT D.DEPT_NAME, COUNT(E.EMP_ID) AS EMP_COUNT
FROM EMPLOYEES E 
JOIN DEPARTMENTS D
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME
HAVING COUNT(E.EMP_ID) > 2;

--Display employees without a department
SELECT E.EMP_ID,E.EMP_NAME,E.SALARY
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPT_ID = D.DEPT_ID
WHERE D.DEPT_ID IS NULL;